[[redirects]]
  from = "/api/check-repository"
  to = '/.netlify/functions/check-repository'
  status = 200

[build]
  functions = "functions"


[[plugins]]
  package = "@netlify/plugin-functions-install-core"